# 核心：激活指定的开发环境
spring:
  profiles:
    active: dev # 告诉 Spring Boot，去读取 application-dev.yml

# 下面放所有环境都通用（不用改）的配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.cloud.hospital.system.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档生成规则配置
springdoc:
  api-docs:
    enabled: true # 开启 OpenAPI 规范生成
  swagger-ui:
    enabled: true
  packages-to-scan: com.cloud.hospital.system.controller # 只扫描我们自己写的接口