# 开发环境的端口
server:
  port: 8080

spring:
  # 开发环境的数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_hospital?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root #
  rabbitmq:
      # 同样通过 localhost 访问映射出来的 5672 端口
      host: localhost
      port: 5672
      # 默认用户名和密码都是 guest
      username: guest
      password: guest
      # 建议配置一个监听器，确保连接成功
      listener:
        simple:
          acknowledge-mode: manual
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456
      database: 0
      timeout: 5000ms # 连接超时时间
      lettuce:
        pool:
          max-active: 8    # 最大连接数
          max-idle: 8      # 最大空闲连接
          min-idle: 0      # 最小空闲连接
          max-wait: 100ms  # 连接池满时，最大等待时间

mybatis-plus:
  configuration:
    # 强烈建议：只在 dev 开发环境下开启 SQL 打印日志，线上 prod 环境一定要关掉（为了性能和安全）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true